In [1]:
import pandas as pd
import librosa
import soundfile as SF
import pickle
with open('/export/c09/lavanya/languageIdentification/test_pickles/segments.pkl', 'rb') as f:
    seg_df = pickle.load(f)

FileNotFoundError: [Errno 2] No such file or directory: '/export/c09/lavanya/languageIdentification/test_pickles/segments.pkl'

In [6]:
seg_df['segmented_audio'][0]

'/export/c09/lavanya/languageIdentification/segments/TTS_P91182TT_VCST_ECxxx_01_AO_48503281_v001_R004_CRR_MERLIon-CCS_segment_0.wav'

In [3]:
seg_df.head()

,segmented_audio,language_tag,overlap_diff_lang,length,utt_id
0,/export/c09/lavanya/languageIdentification/seg...,English,False,1580,a1
1,/export/c09/lavanya/languageIdentification/seg...,English,False,3190,a4
2,/export/c09/lavanya/languageIdentification/seg...,English,False,1020,a8
3,/export/c09/lavanya/languageIdentification/seg...,English,False,1160,a11
4,/export/c09/lavanya/languageIdentification/seg...,English,False,3480,a14

In [7]:
# Define the old and new path prefixes
old_prefix = '/export/c09/lavanya/languageIdentification/segments/'
new_prefix = '/export/c09/lavanya/languageIdentification/test_segments_40/'

# Update the 'segmented_audio' column
seg_df['segmented_audio'] = seg_df['segmented_audio'].replace(to_replace=old_prefix, value=new_prefix, regex=True)
seg_df['segmented_audio'][0]

'/export/c09/lavanya/languageIdentification/test_segments_40/TTS_P91182TT_VCST_ECxxx_01_AO_48503281_v001_R004_CRR_MERLIon-CCS_segment_0.wav'

In [8]:
# Get unique values and count them
unique_values = seg_df['segmented_audio'].unique()
unique_count = len(unique_values)

# Print the count of unique values
print(f"Number of unique values in 'segmented_audio': {unique_count}")

Number of unique values in 'segmented_audio': 40

In [9]:
test_embeddings_base = '/export/c09/lavanya/languageIdentification/test_embedding_40/'

# Define a function to generate the embedding path
def get_embedding_path(segment_path):
    # Extract the file name from the segment path
    file_name = segment_path.split('/')[-1]
    # Replace the base path with the embedding path
    embedding_path = test_embeddings_base + f'emb_{file_name.replace(".wav", "")}.pt'
    return embedding_path

# Apply the function to create the 'embedding' column
seg_df['embedding'] = seg_df['segmented_audio'].apply(get_embedding_path)

In [11]:
seg_df.head()

,segmented_audio,language_tag,overlap_diff_lang,length,utt_id,embedding
0,/export/c09/lavanya/languageIdentification/tes...,English,False,1580,a1,/export/c09/lavanya/languageIdentification/tes...
1,/export/c09/lavanya/languageIdentification/tes...,English,False,3190,a4,/export/c09/lavanya/languageIdentification/tes...
2,/export/c09/lavanya/languageIdentification/tes...,English,False,1020,a8,/export/c09/lavanya/languageIdentification/tes...
3,/export/c09/lavanya/languageIdentification/tes...,English,False,1160,a11,/export/c09/lavanya/languageIdentification/tes...
4,/export/c09/lavanya/languageIdentification/tes...,English,False,3480,a14,/export/c09/lavanya/languageIdentification/tes...

In [12]:
seg_df['embedding'][0]

'/export/c09/lavanya/languageIdentification/test_embedding_40/emb_TTS_P91182TT_VCST_ECxxx_01_AO_48503281_v001_R004_CRR_MERLIon-CCS_segment_0.pt'

In [13]:
seg_df['segmented_audio'][0]

'/export/c09/lavanya/languageIdentification/test_segments_40/TTS_P91182TT_VCST_ECxxx_01_AO_48503281_v001_R004_CRR_MERLIon-CCS_segment_0.wav'

In [14]:
seg_df.shape

(40, 6)

In [15]:
columns = ['segmented_audio', 'embedding', 'language_tag', 'overlap_diff_lang', 'length', 'utt_id']
seg_df = seg_df[columns]

In [16]:
seg_df.head()

,segmented_audio,embedding,language_tag,overlap_diff_lang,length,utt_id
0,/export/c09/lavanya/languageIdentification/tes...,/export/c09/lavanya/languageIdentification/tes...,English,False,1580,a1
1,/export/c09/lavanya/languageIdentification/tes...,/export/c09/lavanya/languageIdentification/tes...,English,False,3190,a4
2,/export/c09/lavanya/languageIdentification/tes...,/export/c09/lavanya/languageIdentification/tes...,English,False,1020,a8
3,/export/c09/lavanya/languageIdentification/tes...,/export/c09/lavanya/languageIdentification/tes...,English,False,1160,a11
4,/export/c09/lavanya/languageIdentification/tes...,/export/c09/lavanya/languageIdentification/tes...,English,False,3480,a14

In [18]:
seg_df.to_pickle('/export/c09/lavanya/languageIdentification/test_pickles_40/updated_segments_with_embeddings.pkl')

In [3]:
import pandas as pd
import librosa
import soundfile as SF
import pickle
with open('/export/c09/lavanya/languageIdentification/pickles/segments_main_1.pkl', 'rb') as f:
    seg_df = pickle.load(f)

In [4]:
seg_df.head()

,segmented_audio,language_tag,overlap_diff_lang,length,utt_id
0,/export/c09/lavanya/languageIdentification/seg...,English,False,1580,a1
1,/export/c09/lavanya/languageIdentification/seg...,English,False,3190,a4
2,/export/c09/lavanya/languageIdentification/seg...,English,False,1020,a8
3,/export/c09/lavanya/languageIdentification/seg...,English,False,1160,a11
4,/export/c09/lavanya/languageIdentification/seg...,English,False,3480,a14
...,...,...,...,...,...
49667,/export/c09/lavanya/languageIdentification/seg...,English,False,840,a1144
49668,/export/c09/lavanya/languageIdentification/seg...,English,False,1840,a1147
49669,/export/c09/lavanya/languageIdentification/seg...,English,False,1360,a1150
49670,/export/c09/lavanya/languageIdentification/seg...,English,False,1540,a1153
49671,/export/c09/lavanya/languageIdentification/seg...,English,False,900,a1160

In [9]:
# Check if the segmented_audio column contains the specific file path
mask = seg_df['segmented_audio'] == '/export/c09/lavanya/languageIdentification/segments/TTS_P96375TT_VCST_Exxxx_01_AO_54731399_v001_R007_CRR_MERLIon-CCS_segment_1738.wav'

# Print the rows where the condition is True
print(seg_df[mask])

                                        segmented_audio language_tag  \
1391  /export/c09/lavanya/languageIdentification/seg...      English

      overlap_diff_lang  length utt_id
1391              False    4559   a657